### ISSUE TITLE
SKR 3 ez BLTouch fails to power on or funtion

### ISSUE THREAD

**Issue by RandieBarsteward** [bigtreetech/SKR-3#25]
I have just upgraded to a SKR 3 ez on my Ender 5 Plus and am having issues with my BLTouch v3.1 which does not power on nor respond to any commands. The BLTouch v3.1 in question works on another printer without issue and I have also tested a second BLTouch which also does not function.  I have also tried a different set of wires to eliminate this as a possibility.

The console throws an error which reads: "BLTouch failed to verify sensor state"

My Klipper config can be found [[HERE](https://github.com/RandieBarsteward/Ender-5-Plus-Klipper/blob/main/printer.cfg%20SKR%203%20EZ) (I have updated this with recent changes)]
![PXL_20220920_161657132](https://user-images.githubusercontent.com/39021056/191807608-5a280f4a-9414-4fe4-8442-2b27c689f9ab.jpg)

My BLTouch wiring can be seen above and appears to match the wiring diagram in the manual.

I am starting to suspect a defective board, can anyone sanity check this issue for me?

**Comment by RandieBarsteward** [comment]
Still don't know what the issue was but I reflashed the firmware, removed all wires and started again... And it's working.

**Comment by pixel-shock** [comment]
Hi, I have the same issue. My BLTouch worked before and I did not change any wirings ... switched from the 1.4Turbo to the EZ and upgraded the FW with the pinout given in the schema and in the FW examples ...

**Comment by pixel-shock** [comment]
OK, my fault, I set the PIN to the wrong one ...  sorry for that :-/
