### ISSUE TITLE
Ender 3 V2 screen

### ISSUE THREAD

**Issue by Sergeykurm** [bigtreetech/SKR-3#28]
Is it possible to connect the Ender 3 V2 screen without rework? If redoing what and how? I ordered an EZ motherboard, while I'm waiting for the package, I want to set up Marlin.

**Comment by radek8** [comment]
There are no pins defined for this display in the pin file for the SKRV3 board.
You will have to define the pins and make your own connecting cable.

**Comment by Sergeykurm** [comment]
I'm not good at this. Can be more

**Comment by radek8** [comment]
https://github.com/bigtreetech/SKR-3/issues/5

**Comment by Sergeykurm** [comment]
[radek8]   Thank you!

**Comment by Sergeykurm** [comment]
Good afternoon! Has anyone set it up and is it working for you? Please draw in detail how to connect the wires on the SCR 3 EZ board for the Ender 3 V2 screen. ? And what parameters to prescribe in Marlin.? I'll be very grateful!

**Comment by Sergeykurm** [comment]
I'll close the question. Bought TFT50. I will set it up.
