### ISSUE TITLE
Error SKR 3 EZ TFT50 Marlin 2.1.1

### ISSUE THREAD

**Issue by Sergeykurm** [bigtreetech/SKR-3#31]
Hello!
Why does X write ALL LOW. Rearranged the driver in some places, but writes an error on X?
Everything prints fine with this error.

Haven't been able to connect to RS232 TFT50 yet. No connection.
I had to connect to UART3. Works but does not print from SD card SKR 3 EZ. He sees the card, writes that the printing has begun, but there is no heating.
From pronterfeys everything prints well and sees the card. But it gives an error M122 X ALL LOW.

Prints well from the SD TFT screen.
When all wires are connected for Marlin mode, the sound from the screen disappears.
Does not stop printing. Do heaters and coolers turn off when you press STOP?
The motors stop.

Please help set up!

PS Foto https://www.dropbox.com/scl/fo/vnacc8recw12cl2iijdbn/h?dl=0&rlkey=3gpb1whn6d95tbdiy4e67ixs9

**Comment by Sergeykurm** [comment]
ALL LOW solved with this post https://github.com/MarlinFirmware/Marlin/issues/24703

**Comment by Sergeykurm** [comment]
The second issue has been resolved. The heaters didn't turn off. On the screen in the settings I found: cancel gcode - on.
Or in config.ini cancel_gcode_enabled:1

**Comment by radek8** [comment]
If you want to use UART3 to connect to SKR, you have to modify and compile your own FW for TFT

**Comment by Sergeykurm** [comment]
> If you want to use UART3 to connect to SKR, you have to modify and compile your own FW for TFT
> 
> ![image](https://user-images.githubusercontent.com/46979052/199345083-7f73e633-eb33-4042-8adf-0f7c4b8add98.png)
 
Yes, i modity FW as in the example.

**Comment by radek8** [comment]
This is not an example, this is a specific change you have to make before compiling the FW for the TFT display

**Comment by Sergeykurm** [comment]
> This is not an example, this is a specific change you have to make before compiling the FW for the TFT display

This is clear. Question Why is RS232 not working?

**Comment by radek8** [comment]
It looks like you have a faulty pin on the RS232 connector on the processor. Fortunately, the communication can be remapped to another serial input.
You are not the first with this problem.
