### ISSUE TITLE
SKR 3 EZ Second Z not working

### ISSUE THREAD

**Issue by Tomzrk** [bigtreetech/SKR-3#51]
I connected all the wires as described on the website but I can't get the both z steppers to work at all , I had them connected to Zam and Zbm than i switched one of them to E1 and that's the only stepper working now , any ideas ?

**Comment by SomeUnknownUser** [comment]
Please check the wires.
I seem to have the same problem but after swapping ZA and ZB the Problem moved to the other stepper.
Then I moved the whole cable from Z1 and Z2 and the problem moved again. That means the cables from z1 and z2 seems to be different on my printer.

Use your printers manual and double check that.

**Comment by Tomzrk** [comment]
I did check all the cables , Everything else work fine

**Comment by SomeUnknownUser** [comment]
Is it always just ZB. that is not working or does it change sometimes?

**Comment by Tomzrk** [comment]
It's Za and Zb both are not working but whenever i connect one of them to the E1 it works fine

**Comment by SomeUnknownUser** [comment]
Not sure if this is the reason why, but… did you set the little diag jumper? If yes: what happened if you remove them.

did you also play around mit the current?

**Comment by Tomzrk** [comment]
I didn't touch any jumpers , i had no idea about it and i did lower the current to 650 instead of 800
