### ISSUE TITLE
pins_debugging error

### ISSUE THREAD

**Issue by WebDesignerlol** [bigtreetech/SKR-3#6]
If I enable #define pins_debugging I receive:
``
\marlin\skr-3\skr-3\firmware\marlin-bugfix-2.0.9.3.x\marlin\src\hal\stm32\pinsdebug.h:168:14: error: 'NUM_ANALOG_FIRST' was not declared in this scope; did you mean 'NUM_ANALOG_INPUTS'?
  168 |   Ard_num -= NUM_ANALOG_FIRST;
      |              ^~~~~~~~~~~~~~~~
      |              NUM_ANALOG_INPUTS
``
Any chance this could be patched?
Thank you.

**Comment by dstrohl** [comment]
Can someone at least provide the correct setting for NUM_ANALOG_FIRST?

**Comment by Bakorlam** [comment]
@dstrohl @WebDesignerlol 
From the Marlin 2.1.1 - variant_MARLIN_STM32H743VX.h
#define NUM_ANALOG_INPUTS       16

**Comment by WebDesignerlol** [comment]
This is the fix that worked for me:
buildroot\share\PlatformIO\variants\MARLIN_H743Vx\variant_MARLIN_STM32H743VX.h
		#define NUM_ANALOG_FIRST        PA0
