### ISSUE TITLE
Hardware (SKR 3 EZ)/BIGTREETECH SKR 3 EZ V1.0 3D.pdf is blank

### ISSUE THREAD

**Issue by jimmyeao** [bigtreetech/SKR-3#85]
Trying to look at the manual for the BIGTREETECH SKR 3 EZ V1.0 but the pdf is blank:
![image](https://github.com/bigtreetech/SKR-3/assets/5197831/de629a11-bbc8-4387-a99d-5845086701ed)

**Comment by thisiskeithb** [comment]
Same issue reported in https://github.com/bigtreetech/SKR-3/issues/61

[BIGTREETECH SKR 3 EZ V1.0 3D.pdf](https://github.com/bigtreetech/SKR-3/blob/master/Hardware%20(SKR%203%20EZ)/BIGTREETECH%20SKR%203%20EZ%20V1.0%203D.pdf) is an interactive PDF with multimedia/3D content that cannot be viewed through your browser. Download the PDF and view in Acrobat Reader directly:

<img width="1166" alt="image" src="https://github.com/bigtreetech/SKR-3/assets/13375512/488b5c5c-4e0f-412d-a6ab-aa7c90232402">

All of BTT's PDFs with "3D" in the name will be like this.

**Comment by jimmyeao** [comment]
Found it, the manual is located in the wrong place in the directory tree:
![image](https://github.com/bigtreetech/SKR-3/assets/5197831/c70846a0-74e9-475f-a368-19bfc7b10d1e)
Its located inthe stander SKR 3 section not the EZ section
